/**
 * AdLinkr
 * A URL shortening tool for digital marketers
 * https://github.com/jodylecompte/AdLinkr
 * License: MIT
 *
 * Written by Jody LeCompte <jody@jodylecompte.com
 * Website: https://jodylecompte.com
 */

module.exports = [
    {
        _id: 10000,
        url: 'https://google.com',
        shortCode: 'goodCode',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10001,
        url: 'https://jodylecompte.com',
        shortCode: 'jody',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10002,
        url: 'https://jodylecompte.com',
        shortCode: 'jody2',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10003,
        url: 'https://jodylecompte.com',
        shortCode: 'jody3',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10004,
        url: 'https://jodylecompte.com',
        shortCode: 'jody4',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10005,
        url: 'https://jodylecompte.com',
        shortCode: 'jody5',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10006,
        url: 'https://jodylecompte.com',
        shortCode: 'jody6',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10007,
        url: 'https://jodylecompte.com',
        shortCode: 'jody7',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10008,
        url: 'https://jodylecompte.com',
        shortCode: 'jody8',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10009,
        url: 'https://jodylecompte.com',
        shortCode: 'jody9',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 100100,
        url: 'https://google.com',
        shortCode: 'goodCode100',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10011,
        url: 'https://jodylecompte.com',
        shortCode: 'jody11',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10012,
        url: 'https://jodylecompte.com',
        shortCode: 'jody12',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10013,
        url: 'https://jodylecompte.com',
        shortCode: 'jody13',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10014,
        url: 'https://jodylecompte.com',
        shortCode: 'jody14',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10015,
        url: 'https://jodylecompte.com',
        shortCode: 'jody15',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10016,
        url: 'https://jodylecompte.com',
        shortCode: 'jody16',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10017,
        url: 'https://jodylecompte.com',
        shortCode: 'jody17',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10018,
        url: 'https://jodylecompte.com',
        shortCode: 'jody18',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10019,
        url: 'https://jodylecompte.com',
        shortCode: 'jody19',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10020,
        url: 'https://google.com',
        shortCode: 'goodCode20',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10021,
        url: 'https://jodylecompte.com',
        shortCode: 'jody21',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10022,
        url: 'https://jodylecompte.com',
        shortCode: 'jody22',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10023,
        url: 'https://jodylecompte.com',
        shortCode: 'jody23',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10024,
        url: 'https://jodylecompte.com',
        shortCode: 'jody24',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10025,
        url: 'https://jodylecompte.com',
        shortCode: 'jody25',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10026,
        url: 'https://jodylecompte.com',
        shortCode: 'jody26',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10027,
        url: 'https://jodylecompte.com',
        shortCode: 'jody27',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10028,
        url: 'https://jodylecompte.com',
        shortCode: 'jody28',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
    {
        _id: 10029,
        url: 'https://jodylecompte.com',
        shortCode: 'jody29',
        utmSource: 'TestSource',
        utmMedium: 'TestMedium',
        utmTerm: 'TestTerm',
        utmContent: 'TestContent',
    },
];
